### ISSUE TITLE
not working for me. If u can help it would be gr8 :)

### ISSUE THREAD

**Issue by ChopChoP534** [Ayfri/advanced-command-handler-examples#2]
I have this in my main bot file 
```
const {CommandHandler} = require('advanced-command-handler');

CommandHandler.create({
	commandsDir: 'commands',
	eventsDir: 'events',
	prefixes: ['.'],
});
```
Dm on discord cause I dont check github that much 
ChopChoP#0069

**Comment by Ayfri** [comment]
No I won't DM you, but what is the problem ?

**Comment by ChopChoP534** [comment]
its just not taking files from there

**Comment by ChopChoP534** [comment]
> No I won't DM you, but what is the problem ?

uhh.. it will be slow here

**Comment by Ayfri** [comment]
Can you explain more precisely what happens?
Does the bot works, do the commands are loaded, what is your arborescence, etc.
If you can show me your full project via a Github repo it would be easier

**Comment by ChopChoP534** [comment]
the bot comes online but when i try to use command it is not working.
and I cant show via repo cause I keep editing it.

**Comment by Ayfri** [comment]
Do you created a message event that executes commands ?
Because it's not integrated into the command handler.
There is examples of this into this repo.

**Comment by ChopChoP534** [comment]
ohhk i got it
